import HeroUIProvider from "@/providers/HeroUIProvider";
import ProviderQuery from "@/providers/QueryProvider";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";

const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-publicSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={publicSans.className}>
        <ThemeProvider>
          <ProviderQuery>
            <HeroUIProvider>{children}</HeroUIProvider>
          </ProviderQuery>
        </ThemeProvider>
      </body>
    </html>
  );
}
