import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import FloatingBot from "@/components/layout/floatingBot/floatingBot";



import HeroUIProvider from "@/providers/HeroUIProvider";

const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-publicSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={publicSans.className}
      >
        <HeroUIProvider>
          {children}
          <FloatingBot/>
          </HeroUIProvider>
      </body>
    </html>
  );
}
